// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVvhdLwWErSQbcZWB9KGUZTAgTiIfR1c',
    appId: '1:194018823339:web:e3775836f6870b2f86fbee',
    messagingSenderId: '194018823339',
    projectId: 'carwash-636ae',
    authDomain: 'carwash-636ae.firebaseapp.com',
    storageBucket: 'carwash-636ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNK8258RAawGEIYBUdG6Y31uMZ1NiQIc',
    appId: '1:194018823339:android:1bd8547899da61db86fbee',
    messagingSenderId: '194018823339',
    projectId: 'carwash-636ae',
    storageBucket: 'carwash-636ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjoejwy6zDAl0ipPATgCXn90MlkxTW76I',
    appId: '1:194018823339:ios:4c599811cedf4fbf86fbee',
    messagingSenderId: '194018823339',
    projectId: 'carwash-636ae',
    storageBucket: 'carwash-636ae.appspot.com',
    iosClientId: '194018823339-agkj5rch7o2rvekp5m15elfk2hgdumuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTextSpeach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjoejwy6zDAl0ipPATgCXn90MlkxTW76I',
    appId: '1:194018823339:ios:4c599811cedf4fbf86fbee',
    messagingSenderId: '194018823339',
    projectId: 'carwash-636ae',
    storageBucket: 'carwash-636ae.appspot.com',
    iosClientId: '194018823339-agkj5rch7o2rvekp5m15elfk2hgdumuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTextSpeach',
  );
}
